name: anime
description: "Flutter anime recommendation app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  cached_network_image: ^3.4.1
  logger: ^2.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true